name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies for APP-1
        run: npm install
        working-directory: APP-1  # Update to the correct folder name

      - name: Build APP-1
        run: npm run build
        working-directory: APP-1  # Update to the correct folder name

      - name: Install Dependencies for APP-2
        run: npm install
        working-directory: APP-2  # Update to the correct folder name

      - name: Build APP-2
        run: npm run build
        working-directory: APP-2  # Update to the correct folder name

      - name: Deploy to AWS EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USERNAME }}
          key: ${{ secrets.AWS_PRIVATE_KEY }}
          source: "CI-CD/*" # Correct source path
          target: "/home/ubuntu/app-1/CI-CD"  # Correct target path

      - name: Restart Server on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USERNAME }}
          key: ${{ secrets.AWS_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/app-1/CI-CD
            pm2 restart all || pm2 start npm --name "APP-1" -- start
            pm2 start npm --name "APP-2" -- start --prefix APP-2
